
server:
  port: ${server_port}

spring:
  application:
    name: 01_learn
  mongodb:
    uri: ${mongodb_uri}

jwt:
  secret: ${jwt_secret}
  expiration: ${jwt_expiration}
  refreshTokenExpire: ${jwt_refresh_expire}
