server:
  port: 8801

spring:
  application:
    name: 01_learn

  datasource:
    url: jdbc:mysql://localhost:3306/basic
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: OPKzNJRJA9WbKIjQ4ymEOFsRHjq3F9Cr1Ve2EQBdGPo
  expiration: 3600000
